####propagate.py   

#to come from propopt package 
    
#######FUNCTION THAT CALCULATES THE RS INTEGRAL PROPAGATOR XY

#######FUNCTION THAT CALCULATES THE RS INTEGRAL PROPAGATOR XZ 

#######FUNCTION THAT CALCULATES THE RS CONV. PROPAGATOR CO

#######FUNCTION THAT CALCULATES THE FRESNEL APPROX.INTEGRAL 

#######FUNCTION THAT CALCULATES THE FRAUNHOFER APPROX. INTEGRAL